language: java

jdk:
  - oraclejdk8

script:
    - ./gradlew clean build
    - ./gradlew increaseBuildNumber
    - git commit -am 'increase build version'
    - git push origin HEAD

env:
  DOCKER_COMPOSE_VERSION: 1.4.2

services:
  - docker

before_install:
  - docker pull neo4j
  - sudo rm -f /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - openssl aes-256-cbc -K $encrypted_f582ed59565f_key -iv $encrypted_f582ed59565f_iv -in github_deploy_key.enc -out github_deploy_key -d
