version: "2"
services:
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none

  tntserver:
    build: .
    image: "tntserver:1.0.0"
    ports:
      - "8080:8080"
  #  command: watch df -h
    links:
      - neo4j

